/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Table;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian
 */
public class Table_application extends javax.swing.JFrame {

    /**
     * Creates new form Table_application
     */
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    
    
    
    public Table_application() {
        initComponents();
        DefaultTableModel mt = (DefaultTableModel) jTable1.getModel();
        String ids [] = {"No_control" ,"Nombre","Domicilio","Ciudad","Edad" ,"Oficio"};
        mt.setColumnIdentifiers(ids);
        
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
        System.out.println("Hola");
        mt.setColumnIdentifiers(ids);
        try {
            // Configura la conexión a la base de datos MySQL
            String url = "jdbc:mysql://localhost:3306/test";
            String usuario = "root";
            String contraseña = "root";

            // Establece la conexión
            connection = DriverManager.getConnection(url,usuario,contraseña);
            System.out.println(connection);
            // Crea una declaración SQL
            statement = connection.createStatement();
            
            
            
            // Ejecuta una consulta SQL (por ejemplo, selecciona todos los registros de una tabla)
            String bandera = getSelectedButtonText(buttonGroup1);
            
            String consultaSQL = "";
            //if(bandera == null){
                consultaSQL = "SELECT * FROM datos";
            //}else{
                //consultaSQL = "SELECT * FROM datos WHERE " + bandera + " " + jTextField1.getText();
            //}
            
            resultSet = statement.executeQuery(consultaSQL);
            
            System.out.println("Result Test:" + resultSet);
            // Procesa los resultados
            while (resultSet.next()) {
                int no_control = resultSet.getInt("No_Control");
                String nombre = resultSet.getString("Nombre");
                String domicilio = resultSet.getString("Domicilio");
                String ciudad = resultSet.getString("Ciudad");
                int edad = resultSet.getInt("Edad");
                String oficio = resultSet.getString("Oficio");
                
                mt.addRow(new Object[]{no_control,nombre,domicilio,ciudad,edad,oficio});
                //int id = resultSet.getInt("id");
                //String nombre = resultSet.getString("nombre");
                System.out.println("No. de Control: " + no_control);
                System.out.println("Nombre: " + nombre);
                System.out.println("Domicilio: " + domicilio);
                System.out.println("Ciudad: " + ciudad);
                System.out.println("Edad: " + edad);
                System.out.println("Oficio: " + oficio);
              //  System.out.println("ID: " + id + ", Nombre: " + nombre + ", Edad: " + edad);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Cierra los recursos
            try {
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            };

        }

    );
    jScrollPane1.setViewportView(jTable1);

    jTextField1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField1ActionPerformed(evt);
        }
    });

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText(">");

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("<");

    buttonGroup1.add(jRadioButton3);
    jRadioButton3.setText("<=");

    buttonGroup1.add(jRadioButton4);
    jRadioButton4.setText(">=");

    buttonGroup1.add(jRadioButton5);
    jRadioButton5.setText("=");

    buttonGroup1.add(jRadioButton6);
    jRadioButton6.setText("<>");

    jButton1.setText("Consultar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    buttonGroup2.add(jRadioButton7);
    jRadioButton7.setText("No_control");

    buttonGroup2.add(jRadioButton8);
    jRadioButton8.setText("Nombre");

    buttonGroup2.add(jRadioButton9);
    jRadioButton9.setText("Domicilio");
    jRadioButton9.setToolTipText("");

    buttonGroup2.add(jRadioButton10);
    jRadioButton10.setText("Ciudad");

    buttonGroup2.add(jRadioButton11);
    jRadioButton11.setText("Edad");

    buttonGroup2.add(jRadioButton12);
    jRadioButton12.setText("Oficio");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jRadioButton7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addGap(170, 170, 170))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jRadioButton6)
                            .addGap(42, 42, 42)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(53, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton12)
                        .addComponent(jRadioButton11)
                        .addComponent(jRadioButton10)
                        .addComponent(jRadioButton9)
                        .addComponent(jRadioButton8))
                    .addGap(0, 0, Short.MAX_VALUE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(43, 43, 43)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2)
                .addComponent(jRadioButton3)
                .addComponent(jRadioButton4)
                .addComponent(jRadioButton5)
                .addComponent(jRadioButton6))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(jRadioButton7))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jRadioButton9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButton11)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton12)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel mt = (DefaultTableModel) jTable1.getModel();
        String ids [] = {"No_control" ,"Nombre","Domicilio","Ciudad","Edad" ,"Oficio"};
        mt.setColumnIdentifiers(ids);
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
        System.out.println("Hola");
        try {
            // Configura la conexión a la base de datos MySQL
            String url = "jdbc:mysql://localhost:3306/test";
            String usuario = "root";
            String contraseña = "root";

            // Establece la conexión
            connection = DriverManager.getConnection(url, usuario, contraseña);
            System.out.println(connection);
            // Crea una declaración SQL
            statement = connection.createStatement();
            
            while (mt.getRowCount() > 0) {
            mt.removeRow(0);
            }

            // Ejecuta una consulta SQL (por ejemplo, selecciona todos los registros de una tabla)
            String columna = getSelectedButtonText(buttonGroup2);
            String condicion = getSelectedButtonText(buttonGroup1);
            String consultaSQL = "";
            if (columna == null || condicion == null) {
                consultaSQL = "SELECT * FROM datos";
            } else if (columna == "Edad"){
                consultaSQL = "SELECT * FROM test.datos WHERE " + columna + " " + condicion + " " + jTextField1.getText();
            }else{
                consultaSQL = "SELECT * FROM test.datos WHERE " + columna + " " + condicion + " '" + jTextField1.getText() + "'";

            }
            
            System.out.println(consultaSQL);

            resultSet = statement.executeQuery(consultaSQL);

            System.out.println("Result Test:" + resultSet);
            // Procesa los resultados
            while (resultSet.next()) {
                int no_control = resultSet.getInt("No_Control");
                String nombre = resultSet.getString("Nombre");
                String domicilio = resultSet.getString("Domicilio");
                String ciudad = resultSet.getString("Ciudad");
                int edad = resultSet.getInt("Edad");
                String oficio = resultSet.getString("Oficio");

                mt.addRow(new Object[]{no_control, nombre, domicilio, ciudad, edad, oficio});
                //int id = resultSet.getInt("id");
                //String nombre = resultSet.getString("nombre");
                System.out.println("No. de Control: " + no_control);
                System.out.println("Nombre: " + nombre);
                System.out.println("Domicilio: " + domicilio);
                System.out.println("Ciudad: " + ciudad);
                System.out.println("Edad: " + edad);
                System.out.println("Oficio: " + oficio);
                //  System.out.println("ID: " + id + ", Nombre: " + nombre + ", Edad: " + edad);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // Cierra los recursos
            try {
                if (resultSet != null) {
                    resultSet.close();
                }
                if (statement != null) {
                    statement.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table_application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table_application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table_application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table_application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table_application().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
